name: football_activity
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_foreground: "assets/app_icon_foreground.png"
  adaptive_icon_background: "assets/app_icon_background.png"

flutter_native_splash:
  color: "#ffffff"  # Sau culoarea de fundal dorită
  image: assets/splash_icon.png  # Imaginea pentru splash screen
  android: true
  ios: true
  android_12:
    image: assets/splash_icon.png  # Imagine pentru Android 12+
    icon_background_color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/background.png